<a href="https://colab.research.google.com/github/Nael1906/DAA3/blob/main/DAA%20Pertemuan%203.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [52]:
#Menampilkan data didalam List

import numpy as np
import datetime


date = datetime.date.today()

aList1= ["Najib",
         2022071069,
         "Informatika",
         "Desain Analisis Algoritma",
         str(date),
         "Universitas Pembangunan Jaya" ]

aList2 = ["Tamboto",
          2022071008,
          "Informatika",
          "Desain Analisis Algoritma",
          str(date),
          "Universitas Pembangunan Jaya"]

aList3 = ["Daffa",
          2022071006,
          "Informatika",
          "Desain Analisis Algoritma",
          str(date),
          "Universitas Pembangunan Jaya"]

print(aList1)
print(date)

['Najib', 2022071010, 'Tangerang Selatan', '2023-09-13', 'Desain Analisis Algoritma', 'Universitas Pembangunan Jaya']
2023-09-13


In [75]:
#Menampilkan Nim mahasiswa

import numpy as np
import datetime


date = datetime.date.today()

aList1= ["Najib",
         2022071069,
         "Informatika",
         "Desain Analisis Algoritma",
         str(date),
         "Universitas Pembangunan Jaya" ]

aList2 = ["Tamboto",
          2022071008,
          "Informatika",
          "Desain Analisis Algoritma",
          str(date),
          "Universitas Pembangunan Jaya"]

aList3 = ["Daffa",
          2022071006,
          "Informatika",
          "Desain Analisis Algoritma",
          str(date),
          "Universitas Pembangunan Jaya"]

print("NIM Najib adalah : ", aList1[1])
print(date)

NIM Najib adalah :  2022071010
2023-09-13


In [76]:
#Menampilkan Universitas Mahasiswa

import numpy as np
import datetime


date = datetime.date.today()

aList1= ["Najib",
         2022071069,
         "Informatika",
         "Desain Analisis Algoritma",
         str(date),
         "Universitas Pembangunan Jaya" ]

aList2 = ["Tamboto",
          2022071008,
          "Informatika",
          "Desain Analisis Algoritma",
          str(date),
          "Universitas Pembangunan Jaya"]

aList3 = ["Daffa",
          2022071006,
          "Informatika",
          "Desain Analisis Algoritma",
          str(date),
          "Universitas Pembangunan Jaya"]
print("Najib Berkuliah di : ", aList1[5])
print(date)

Najib Berkuliah di :  Universitas Pembangunan Jaya
2023-09-13


In [82]:
#Melakukan Slicing untuk menampilkan Prodi dan NIM mahasiswa

import numpy as np
import datetime


date = datetime.date.today()

aList1= ["Najib",
         2022071069,
         "Informatika",
         "Desain Analisis Algoritma",
         str(date),
         "Universitas Pembangunan Jaya" ]

aList2 = ["Tamboto",
          2022071008,
          "Informatika",
          "Desain Analisis Algoritma",
          str(date),
          "Universitas Pembangunan Jaya"]

aList3 = ["Daffa",
          2022071006,
          "Informatika",
          "Desain Analisis Algoritma",
          str(date),
          "Universitas Pembangunan Jaya"]

print("Ini adalah NIM dan Prodi Najib : ", aList1[1:3])
print(date)

Ini adalah NIM dan Prodi Najib :  [2022071069, 'Informatika']
2023-09-13


In [81]:
#Melakukan Iterasi

bin_Mahasiswa = ["Najib", "Fahmi", "Daffa", "Ican"]

for aMahasiswa in bin_Mahasiswa:
  print("UPJ " + aMahasiswa)


UPJ Najib
UPJ Fahmi
UPJ Daffa
UPJ Ican


In [85]:
#Nested Tupel

nilaiAwal = (100)
nilaiKedua = (200,400,600)
nilaiKetiga = (300)
nilaiKeempat = (400,800)

nilai = (nilaiKedua, nilaiKeempat)
print(nilai)

((200, 400, 600), (400, 800))


In [99]:
#DICTIONARY
import numpy as np

bin_mahasiswa = {"NAMA"  :"Najib",
              "NIM " : "2022071069",
              "Prodi " : "Informatika",
              "Mata Kuliah" : "Desain Analisis Algoritma",
              "Universitas" : "Universitas Pembangunan Jaya"}
print(bin_mahasiswa)

{'NAMA': 'Najib', 'NIM ': '2022071069', 'Prodi ': 'Informatika', 'Mata Kuliah': 'Desain Analisis Algoritma', 'Universitas': 'Universitas Pembangunan Jaya'}


In [105]:
#Inisiasi Set
set_01 = {4,5,6,2}
print("set_01 = ", set_01)

#inisiasi mengubah list menjadi set
set_02 = set()
set_03 = set([2,1,4,3])

print(type(set_02))
print("set_03 = ", set_03)

print("\nmenambah")
set_01.add(576)
print(set_01)

print("\nmenghapus")
set_01.discard(6)
print(set_01)

print("\nunion")
print(set_01|set_03)
print("\nintersection")
print(set_01&set_03)

print("\ndifference")
print(set_01-set_03)

print("\nsymmetric difference")
print(set_01^set_03)

set_01 =  {2, 4, 5, 6}
<class 'set'>
set_03 =  {1, 2, 3, 4}

menambah
{576, 2, 4, 5, 6}

menghapus
{576, 2, 4, 5}

union
{576, 1, 2, 3, 4, 5}

intersection
{2, 4}

difference
{576, 5}

symmetric difference
{576, 1, 3, 5}


In [107]:
red = {"dandelions", "leaves", "fire hydrant"}
green = {"rose", "blood", "leaves", "fire hydrant"}

print(red|green)
print(red&green)

{'rose', 'leaves', 'dandelions', 'fire hydrant', 'blood'}
{'fire hydrant', 'leaves'}


In [109]:
import numpy as np

matrix = np.array([
    [100, 200, 300],
    [700, 600, 500],
    [900, 1000, 800]
    ])

print(matrix)

print("\nTranspose:")
print(matrix.T)

[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]

Transpose:
[[ 100  700  900]
 [ 200  600 1000]
 [ 300  500  800]]


In [116]:
import pandas as pd

df = pd.DataFrame([
    [1, "Informatika", 50, 30, 20],
    [2, "Sistem Informasi", 55, 30, 25],
    [3, "Teknik Sipil", 40, 30, 10]
])

df.columns = ["No", "Prodi", "Mahasiswa", "laki-laki", "Perempuan"]
df.style.hide(axis='index')